services:
   rabbitmqlocal:
      image: bitnami/rabbitmq:4.0.3
      container_name: rabbitmqlocal
      hostname: rabbitmqhost
      #restart: always (optional - prod setup only)
      environment:
         - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
         - RABBITMQ_DEFAULT_PASS=${RABBITMQ_USERPASS}
         #- RABBITMQ_SECURE_PASSWORD=no
         #- RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 268435456 # 268435456 : 256 MB 2147483648 - bits : 2GB
      ports:
         - 15672:15672
         - 5672:5672 # (AMQP)
      #volumes:
      #   - ./rabbitmq:/var/lib/rabbitmq # (prod)
#volumes:
#   ./rabbitmq:  # ( prod)